name: Esegui Script M3U
on:
  workflow_dispatch: # Permette l'avvio manuale via API / Shortcuts
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests bs4 PyGithub
      - run: python tuo_script.py
